name = "Optinum"
uuid = "d9fbbd2f-b07c-4129-9383-1eb96f1f244d"
authors = ["relmo <rachid.elmontassir@etu.enseeiht.fr>"]
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
